### ISSUE TITLE
Join the RegExps party :)

### ISSUE THREAD

**Issue by tunnckoCore** [regexps/regexify#1]
Thought you'd be interested: https://github.com/regexps
Please let me know if you want an invite. :)

Possible answer:

> Thanks, but no thanks. Isn't one regex per npm module a bit overkill?

Nope. It's not necessary to be strictly only one regex per module/repo.
It can be collection like https://github.com/wearefractal/xemplar, which soon will be in the org.

The whole idea behind the **RegExps** project is to have as more as possible in one centralized place with good maintenance and quality. Also, it's target isn't only Node. :)
- one centralized quality place
- the area is just regular expressions - creating, supporting, discussing, tools
- every human being is welcome, any program language
- limitations: almost nothing
- requirements: nothing special, just good practics and maybe `.editorconfig`

As soon as possible, we'll publish some information site.

**Comment by hemanth** [comment]
Sure, Count me in :+1:  :smile: 

Thank you for the invite and the detailed description.

**Comment by tunnckoCore** [comment]
Welcome :) Invite sent.

**Comment by hemanth** [comment]
Done. Thanks.

**Comment by hemanth** [comment]
@tunnckoCore Transferred this repo to regexps.

**Comment by tunnckoCore** [comment]
Cool :) 
Just reminder, dont forget the links in package.json, lol

**Comment by hemanth** [comment]
heh heh, ill fix them.
